# simple_api/docker-compose.yml
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: simple_api_dev
    volumes:
      - db_data:/var/lib/postgresql/data

  web:
    build: .
    command: bundle exec rails server -b 0.0.0.0
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/simple_api_dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app                     
      - bundle_cache:/usr/local/bundle 

    depends_on:
      - db

volumes:
  db_data:
  bundle_cache:
